apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: activemq
    spec:
      containers:
      - image: tba-activemq:latest
        name: activemq
        ports:
        - containerPort: 5601
        - containerPort: 61616
        - containerPort: 8161
        - containerPort: 5672
        - containerPort: 61613
        - containerPort: 1883
        - containerPort: 61614
        resources: {}
      restartPolicy: Always
status: {}